### ISSUE TITLE
Pls help, your project doesn't work

### ISSUE THREAD

**Issue by Zack228** [adainrivers/d4-texture-extractor#2]
....

**Comment by Igrom4ek** [comment]
Error: ENOENT: no such file or directory, scandir 'E:\d4-texture-extractor-main\gamedata\Base\meta\Texture'
    at async Object.readdir (node:internal/fs/promises:950:18)
    at async getTextureDataFilesAsync (E:\d4-texture-extractor-main\functions\getTextureDataFilesAsync.js:6:19)
    at async main (E:\d4-texture-extractor-main\index.js:27:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'E:\\d4-texture-extractor-main\\gamedata\\Base\\meta\\Texture'
}

**Comment by adainrivers** [comment]
you need https://github.com/blizzhackers/d4data
